# Datos de la base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/akdokm_db
spring.datasource.username=postgres
spring.datasource.password=Leo19442.

# Configuración de JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
logging.level.org.hibernate.orm.jdbc.bind=trace
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Evitar errores de CORS con Angular (Puerto 4200)
server.port=8080

